---
abstract: 'Web Server Gateway Interface and HTTP Server Engine Drivers (Yet Another Catalyst::Engine)'
author:
  - 'Kazuhiro Osawa <yappo <at> shibuya <döt> pl>'
build_requires:
  File::Temp: 0.20
  HTTP::Request::AsCGI: 0
  IO::File: 1.14
  IO::Scalar: 0
  IO::Socket: 1.3
  IO::Socket::INET: 0
  Test::More: 0
  Test::TCP: 0.02
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.790'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Engine
no_index:
  directory:
    - examples
    - inc
    - t
recommends:
  Errno: 1.0901
  FCGI: 0.67
  HTTP::Server::Simple: 0.34
  IO::Scalar: 2.11
  IO::Socket::INET: 1.31
  POE: 1.0003
  POE::Filter::HTTPD: 1.2387
requires:
  Any::Moose: 0.05
  CGI::Simple::Cookie: 1.103
  Class::Method::Modifiers: 0
  File::Copy: 0
  File::Spec::Unix: 3.2701
  HTTP::Body: 1.05
  HTTP::Headers::Fast: 0.09
  HTTP::Server::Simple: 0.35
  Mouse: 0.19
  MouseX::Types: 0.01
  Scalar::Util: 1.19
  URI: 1.36
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1.5
