---
abstract: 'Web Server Gateway Interface and HTTP Server Engine Drivers (Yet Another Catalyst::Engine)'
author:
  - 'Kazuhiro Osawa <ko@yappo.ne.jp>'
build_requires:
  File::Temp: 0.20
  HTTP::Request::AsCGI: 0
  IO::Scalar: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.750'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTTP-Engine
no_index:
  directory:
    - inc
    - t
    - examples
    - examples
recommends:
  Errno: 0
  FCGI: 0
  HTTP::Request::AsCGI: 0
  HTTP::Server::Simple: 0
  POE: 1.0002
  POE::Filter::HTTPD: 0
requires:
  CGI::Simple::Cookie: 0
  File::Copy: 0
  File::Spec::Unix: 0
  HTTP::Body: 0.9
  HTTP::Headers: 0
  IO::File: 0
  IO::Socket: 0
  Moose: 0.48
  MooseX::Types: 0.04
  Scalar::Util: 0
  URI: 0
version: 0.0.12
