---
abstract: 'Web Server Gateway Interface and HTTP Server Engine Drivers (Yet Another Catalyst::Engine)'
author:
  - 'Kazuhiro Osawa <ko@yappo.ne.jp>'
build_requires:
  File::Temp: 0.20
  HTTP::Request::AsCGI: 0
  IO::Scalar: 0
  Test::More: 0
  Test::TCP: 0
distribution_type: module
generated_by: 'Module::Install version 0.760'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Engine
no_index:
  directory:
    - inc
    - t
    - examples
recommends:
  Errno: 0
  FCGI: 0.67
  HTTP::Server::Simple: 0.34
  IO::Scalar: 0
  POE: 1.0003
  POE::Filter::HTTPD: 1.2387
requires:
  CGI::Simple::Cookie: 0
  File::Copy: 0
  File::Spec::Unix: 0
  HTTP::Body: 1.04
  HTTP::Headers: 0
  IO::File: 1.14
  IO::Socket: 1.3
  Moose: 0.55
  MooseX::Types: 0.04
  Scalar::Util: 0
  URI: 1.36
  URI::QueryParam: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.0.14
